### ISSUE TITLE
Won't compile (detailed error report inside)

### ISSUE THREAD

**Issue by ghost** [tzvetkoff/im2a#1]
I set up my linux environment to have all dependencies, but something called "PixelPacket" causes severe errors. Please help me, I really want to use your software on my armhf Raspberry Pi 2, so far I got everything working there.

> /im2a/im2a$ sudo make install
> Making install in src
> make[1]: Entering directory '/home/ubuntu/im2a/im2a/src'
> g++ -DHAVE_CONFIG_H -I. -I..    -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/include/ImageMagick-7 -g -O2 -MT asciifier.o -MD -MP -MF .deps/asciifier.Tpo -c -o asciifier.o asciifier.cpp
> asciifier.cpp: In member function ‘void im2a::Asciifier::asciify()’:
> asciifier.cpp:173:5: error: ‘PixelPacket’ is not a member of ‘Magick’
>      Magick::PixelPacket _pixels = _image->getPixels(0, 0, _image->columns(),
>      ^
> asciifier.cpp:173:5: note: suggested alternative:
> In file included from /usr/local/include/ImageMagick-7/MagickCore/color.h:21:0,
>                  from /usr/local/include/ImageMagick-7/MagickCore/image.h:21,
>                  from /usr/local/include/ImageMagick-7/MagickCore/draw.h:22,
>                  from /usr/local/include/ImageMagick-7/MagickCore/annotate.h:21,
>                  from /usr/local/include/ImageMagick-7/MagickCore/MagickCore.h:79,
>                  from /usr/local/include/ImageMagick-7/Magick++/Include.h:42,
>                  from /usr/local/include/ImageMagick-7/Magick++.h:10,
>                  from asciifier.h:15,
>                  from asciifier.cpp:19:
> /usr/local/include/ImageMagick-7/MagickCore/pixel.h:204:3: note:   ‘MagickCore::PixelPacket’
>  } PixelPacket;
>    ^
> asciifier.cpp:173:26: error: ‘pixels’ was not declared in this scope
>      Magick::PixelPacket *pixels = _image->getPixels(0, 0, _image->columns(),
>                           ^
> asciifier.cpp:191:13: error: ‘PixelPacket’ is not a member of ‘Magick’
>              Magick::PixelPacket *pixel = pixels + offset;
>              ^
> asciifier.cpp:191:13: note: suggested alternative:
> In file included from /usr/local/include/ImageMagick-7/MagickCore/color.h:21:0,
>                  from /usr/local/include/ImageMagick-7/MagickCore/image.h:21,
>                  from /usr/local/include/ImageMagick-7/MagickCore/draw.h:22,
>                  from /usr/local/include/ImageMagick-7/MagickCore/annotate.h:21,
>                  from /usr/local/include/ImageMagick-7/MagickCore/MagickCore.h:79,
>                  from /usr/local/include/ImageMagick-7/Magick++/Include.h:42,
>                  from /usr/local/include/ImageMagick-7/Magick++.h:10,
>                  from asciifier.h:15,
>                  from asciifier.cpp:19:
> /usr/local/include/ImageMagick-7/MagickCore/pixel.h:204:3: note:   ‘MagickCore::PixelPacket’
>  } PixelPacket;
>    ^
> asciifier.cpp:191:34: error: ‘pixel’ was not declared in this scope
>              Magick::PixelPacket *pixel = pixels + offset;
>                                   ^
> asciifier.cpp:211:32: error: ‘class Magick::Color’ has no member named ‘redQuantum’
>                      pow(color->redQuantum() - gs, 2) +
>                                 ^
> asciifier.cpp:212:32: error: ‘class Magick::Color’ has no member named ‘greenQuantum’
>                      pow(color->greenQuantum() - gs, 2) +
>                                 ^
> asciifier.cpp:213:32: error: ‘class Magick::Color’ has no member named ‘blueQuantum’
>                      pow(color->blueQuantum() - gs, 2)
>                                 ^
> asciifier.cpp:243:36: error: ‘class Magick::Color’ has no member named ‘redQuantum’
>                          pow(color->redQuantum() - pixel->red, 2) +
>                                     ^
> asciifier.cpp:244:36: error: ‘class Magick::Color’ has no member named ‘greenQuantum’
>                          pow(color->greenQuantum() - pixel->green, 2) +
>                                     ^
> asciifier.cpp:245:36: error: ‘class Magick::Color’ has no member named ‘blueQuantum’
>                          pow(color->blueQuantum() - pixel->blue, 2)
>                                     ^
> Makefile:402: recipe for target 'asciifier.o' failed
> make[1]: *_\* [asciifier.o] Error 1
> make[1]: Leaving directory '/home/ubuntu/im2a/im2a/src'
> Makefile:458: recipe for target 'install-recursive' failed
> make: **\* [install-recursive] Error 1

**Comment by tzvetkoff** [comment]
Yeah, ImageMagick 7 broke a thing or two.
Should be OK now (06a97cf2dcb2246ea28ee431bf49a36d3122af2c, tagged `v0.4.0`)

**Comment by ghost** [comment]
Thank you, compiled without any issues today :)
