### ISSUE TITLE
After successful compilation im2a will only display --help when trying to ASCIIfi a file

### ISSUE THREAD

**Issue by ghost** [tzvetkoff/im2a#2]
Sorry to bother you again, but it seems not to work. the same command runs fine with jp2a:

> ubuntu@ubuntu:~$ im2a --height=170 test0.jpg
> 
> im2a 0.4.0
> 
> Convert image files to ASCII art
> Copyright (C) 2013 Latchezar Tzvetkoff
> Distributed under The Beerware License
> 
> Usage:
> im2a [options] <file>
> 
> Options:
>  -h, --help                  Prints this message
> -v, --version               Prints version string
>  -m, --html                  Output HTML
>  -i, --invert                Invert the image
>  -t, --center                Center the image
>  -W, --width=N               Set output width
>  -H, --height=M              Set output height
>  -c, --charset=CHARSET       Set output charset
>  -g, --grayscale             Grayscale output instead of 256-color
>  -R, --red-weight=RW         Set red component weight (default: 0.2989)
>  -G, --green-weight=GW       Set green component weight (default: 0.5866)
>  -B, --blue-weight=BW        Set blue component weight (default: 0.1145)
> 
> Project homepage: https://github.com/tzvetkoff/im2a
> Report bugs to https://github.com/tzvetkoff/im2a/issues
> ubuntu@ubuntu:~$

**Comment by tzvetkoff** [comment]
I'm not sure if I can reproduce this, since this works perfectly on all my boxes - the command line options are handled correctly.
Note that you should provide both `width` and `height` parameters if you need to force constraints. I'm about to make those respect image proportions these days, though...

**Comment by ghost** [comment]
Could you test on a Raspberry Pi 2 with 16.04 LTS? Chances are I messed up, but it compiled without errors, so I don't know. The parameters worked fine for jp2a, so I guess it should have worked. Even if I give both height and width it just prints help.

Anyway, thanks for being very helpful and giving me your time.

**Comment by tzvetkoff** [comment]
Assuming everything is OK, should I assume it's to kea e the issue closed?
