### ISSUE TITLE
Transparency support

### ISSUE THREAD

**Issue by onitake** [tzvetkoff/im2a#5]
It would be very cool if im2a supported transparency.
Partial transparency will be difficult to do, but 100% transparent areas could be mapped to the default terminal background color using `\e[49m`.

It may be necessary to use `▀` and ` ` in addition to `▄` for partial pixels, however.

**Comment by onitake** [comment]
I started working on this, but handling all special cases is tricky:
https://github.com/onitake/im2a/tree/feature/transparency

**Comment by tzvetkoff** [comment]
I also did some work on this today, but haven't finished anything...
I guess I'll finish it tomorrow afternoon or on the weekend.

**Comment by onitake** [comment]
Ok, I did some thinking.
If you take the colour optimisation into account, it will help to consider each 2-pixel pair together with its left neighbour: A 4-pixel block.

Treating transparency as a special case, there are 45 possible combinations, if I didn't miss anything.
I'm gonna cook up a function that covers these, then we can continue from there.

**Comment by tzvetkoff** [comment]
Fixed in 103ff7a (`v0.6.0`)
